name: chat_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  icons_plus: ^5.0.0
  equatable: ^2.0.8
  dio: ^5.9.1
  connectivity_plus: ^7.0.0
  logger: ^2.6.2
  dio_smart_retry: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.1
  build_runner: ^2.11.1

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  
